name: Release Workflow

on:
  push:
    tags:
      - v*

permissions:
  contents: write
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_OWNER: ${{ toLowerCase(github.repository_owner) }}

jobs:
  build:
    name: Build Shoutrrr
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - uses: arnested/go-version-action@v2
        id: go-version

      - name: Set up Go ${{ steps.go-version.outputs.latest }}
        uses: actions/setup-go@v7
        id: go
        with:
          go-version: ${{ steps.go-version.outputs.latest }}
          check-latest: true

      - name: Build
        run: CGO_ENABLED=0 go build -v .

      - name: Test
        run: CGO_ENABLED=0 go test -v -coverprofile=coverage.out -covermode=atomic ./...

      - name: Publish coverage
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ env.IMAGE_OWNER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/386,linux/arm/v6,linux/arm64
          tags: |
            ghcr.io/${{ env.IMAGE_OWNER }}/shoutrrr:${{ github.ref_name }}
            ghcr.io/${{ env.IMAGE_OWNER }}/shoutrrr:latest
            ghcr.io/${{ env.IMAGE_OWNER }}/shoutrrr:amd64-latest
            ghcr.io/${{ env.IMAGE_OWNER }}/shoutrrr:i386-latest
            ghcr.io/${{ env.IMAGE_OWNER }}/shoutrrr:armhf-latest
            ghcr.io/${{ env.IMAGE_OWNER }}/shoutrrr:arm64v8-latest
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          install-only: true

      - name: Show GoReleaser version
        run: goreleaser -v

      - name: Execute goreleaser
        run: |
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} CGO_ENABLED=0 goreleaser --debug --rm-dist